apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - servicemonitor-istio.yaml
  - podmonitor-envoy.yaml
  - prometheus-rules.yaml
  - virtualservice-grafana.yaml
  - virtualservice-prometheus.yaml
  - dashboards/cluster-overview.yaml
  - dashboards/istio-mesh.yaml
  - dashboards/namespace-resources.yaml
