apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  # Namespace
  - namespace.yaml

  # Mosquitto MQTT Broker
  - mosquitto/configmap.yaml
  - mosquitto/pvc.yaml
  - mosquitto/service.yaml
  - mosquitto/deployment.yaml

  # HomeAssistant
  - homeassistant/configmap.yaml
  - homeassistant/pvc.yaml
  - homeassistant/service.yaml
  - homeassistant/deployment.yaml
  - homeassistant/resources/servicemonitor.yaml
  - homeassistant/resources/virtualservice.yaml

  # Zigbee2MQTT
  - zigbee2mqtt/configmap.yaml
  - zigbee2mqtt/pvc.yaml
  - zigbee2mqtt/service.yaml
  - zigbee2mqtt/deployment.yaml
  - zigbee2mqtt/resources/virtualservice.yaml

  # Homebridge
  - homebridge/pvc.yaml
  - homebridge/service.yaml
  - homebridge/deployment.yaml
  - homebridge/resources/virtualservice.yaml
